version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: gilsilva41805/backend:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    
  frontend:
    image: gilsilva41805/frontend:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
