version: '3.9'
services:
  app:
    container_name: golang_container
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - database

 database:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
    restart: on-failure
    volumes:
     - ${PWD}/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432