# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - georeportapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://georeportappregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e2407100ac7c4ef7bac2275b3b71cbb7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d757a5425ba74d90a8b6cb27e5e4f723 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: georeportappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e2407100ac7c4ef7bac2275b3b71cbb7 }}/georeportappregistry.azurecr.io:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'georeportapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_21284fa751994afb93e4c1395469f7f6 }}
        images: 'georeportappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e2407100ac7c4ef7bac2275b3b71cbb7 }}/georeportappregistry.azurecr.io:${{ github.sha }}'