name: Go Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: |
          cd backend  # Navigate to the backend directory
          go mod download

      - name: Run tests
        run: |
          cd backend  # Navigate to the backend directory
          go test -v ./...

